lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(resolve:JWT_EXPIRY)%'
    token_extractors:
        authorization_header:
            enabled: false
        cookie:
            enabled: true
            name: accessToken
    set_cookies:
        accessToken:
            #lifetime: null (defaults to token ttl)
            samesite: strict
            path: /
            #domain: null (null means automatically set by symfony)
            secure: true
            httpOnly: true
            partitioned: false
        refreshToken:
            lifetime: '%env(resolve:JWT_REFRESH_EXPIRY)%'
            samesite: strict
            path: /
            secure: true
            httpOnly: true
            partitioned: false
    remove_token_from_body_when_cookies_used: true
    api_platform:
        check_path: '/auth/login'
        username_path: email
        password_path: password